-- Drop tables --

DROP TABLE IF EXISTS MEASUREMENT;
DROP TABLE IF EXISTS HAS_VITAMIN;
DROP TABLE IF EXISTS VITAMIN;
DROP TABLE IF EXISTS FOLLOWS;
DROP TABLE IF EXISTS PLAN_HAS;
DROP TABLE IF EXISTS DAILY_PLAN;
DROP TABLE IF EXISTS CONSUMES_PRODUCT;
DROP TABLE IF EXISTS CONSUMES_RECIPE;
DROP TABLE IF EXISTS RECIPE_HAS;
DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS NUTRITIONIST;
DROP TABLE IF EXISTS PRODUCT;

-- Drop functions --

DROP FUNCTION discount;
DROP FUNCTION func_getPatients;

-- Drop procedures --

DROP PROCEDURE uspNutritionistReport
DROP PROCEDURE uspPlanDetails;

-- Drop views --
DROP VIEW PLAN_PRODUCT_VIEW;
DROP VIEW PATIENT_PRODUCTS;
DROP VIEW PATIENT_RECIPES;
