-- Drop tables --

DROP TABLE IF EXISTS MEASUREMENT;
DROP TABLE IF EXISTS HAS_VITAMIN;
DROP TABLE IF EXISTS VITAMIN;
DROP TABLE IF EXISTS FOLLOWS;
DROP TABLE IF EXISTS PLAN_HAS;
DROP TABLE IF EXISTS DAILY_PLAN;
DROP TABLE IF EXISTS CONSUMES_PRODUCT;
DROP TABLE IF EXISTS CONSUMES_RECIPE;
DROP TABLE IF EXISTS RECIPE_HAS;
DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS NUTRITIONIST;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ADMIN;

-- Drop functions --

DROP FUNCTION IF EXISTS discount;
DROP FUNCTION IF EXISTS func_getPatients;

-- Drop procedures --

DROP PROCEDURE IF EXISTS uspNutritionistReport
DROP PROCEDURE IF EXISTS uspPlanDetails;
DROP PROCEDURE IF EXISTS uspProductsNotConsumed;
DROP PROCEDURE IF EXISTS uspRecipesNotConsumed;

-- Drop views --
DROP VIEW IF EXISTS PLAN_PRODUCT_VIEW;
DROP VIEW IF EXISTS PATIENT_PRODUCTS;
DROP VIEW IF EXISTS PATIENT_RECIPES;

-- Drop Triggers --
DROP TRIGGER IF EXISTS admin_security;
DROP TRIGGER IF EXISTS patient_validation;